"""
Django settings for chess_analysis project.

Generated by 'django-admin startproject' using Django 4.2.26.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-j7nx7$5zmp+3hcn$xr5dy25x1inion!47g+2%jg3w-smu4i6w$"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "django_celery_results",
    "analysis",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "chess_analysis.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "chess_analysis.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    },
    "evaluations": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get('EVAL_DB_NAME', 'chess_evaluations'),
        "USER": os.environ.get('EVAL_DB_USER', 'chess_user'),
        "PASSWORD": os.environ.get('EVAL_DB_PASSWORD', 'chess_password'),
        "HOST": os.environ.get('EVAL_DB_HOST', 'localhost'),
        "PORT": os.environ.get('EVAL_DB_PORT', '5432'),
        "OPTIONS": {
            "sslmode": os.environ.get('EVAL_DB_SSLMODE', 'prefer'),
        },
    }
}

# Database routing
DATABASE_ROUTERS = ['chess_analysis.db_router.EvaluationsDatabaseRouter']


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Lichess OAuth settings
LICHESS_CLIENT_ID = 'chess-analysis-app'

# GCP Stockfish API settings
# Set this to your deployed GCP Cloud Run URL
GCP_STOCKFISH_URL = 'https://stockfish-api-552342702662.us-west1.run.app'

# DeepSeek API settings for LLM insights
# Get your API key from https://platform.deepseek.com/
DEEPSEEK_API_KEY = os.environ.get('DEEPSEEK_API_KEY', '')

# Login/logout URLs
LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/auth/logout/done/'

# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes max per task

# Chess.com and Lichess API Rate Limiting (global across all workers)
# Both platforms' policy: Serial access is required, parallel triggers 429
# Our strategy: Use Redis locks to ensure only ONE request at a time (serial)
CELERY_TASK_ROUTES = {
    'analysis.tasks.fetch_chess_com_games_task': {
        'queue': 'chess_com_api',
        # No rate limit needed - Redis locks ensure serial access
    },
    'analysis.tasks.fetch_daily_puzzle_task': {
        'queue': 'chess_com_api',
        # Uses same queue as other Chess.com tasks for coordinated rate limiting
    },
    'analysis.tasks.fetch_lichess_games_task': {
        'queue': 'lichess_api',
        # No rate limit needed - Redis locks ensure serial access
    },
}
