# Generated by Django 4.2.26 on 2025-12-30 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lichess_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("lichess_access_token", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameDataSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lichess_username", models.CharField(max_length=100)),
                ("total_games", models.IntegerField(default=0)),
                ("raw_data", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChessGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lichess_game_id", models.CharField(max_length=50, unique=True)),
                ("white_player", models.CharField(max_length=100)),
                ("black_player", models.CharField(max_length=100)),
                ("result", models.CharField(max_length=10)),
                ("opening", models.CharField(blank=True, max_length=200)),
                ("termination", models.CharField(blank=True, max_length=100)),
                ("white_rating", models.IntegerField(blank=True, null=True)),
                ("black_rating", models.IntegerField(blank=True, null=True)),
                ("speed", models.CharField(blank=True, max_length=50)),
                ("played_at", models.DateTimeField(blank=True, null=True)),
                ("user_accuracy", models.FloatField(blank=True, null=True)),
                ("user_color", models.CharField(blank=True, max_length=10)),
                ("stockfish_analyzed", models.BooleanField(default=False)),
                ("raw_game_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game_dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis.gamedataset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-played_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("basic_stats", models.JSONField(default=dict)),
                ("terminations", models.JSONField(default=dict)),
                ("openings", models.JSONField(default=dict)),
                ("accuracy_analysis", models.JSONField(default=dict)),
                ("stockfish_analysis", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("analysis_duration", models.DurationField(blank=True, null=True)),
                ("stockfish_games_analyzed", models.IntegerField(default=0)),
                (
                    "game_dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis.gamedataset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
