# Generated by Django 4.2.26 on 2026-01-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="chess_com_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
