# Generated by Django 4.2.26 on 2026-01-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0002_add_chess_com_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamedataset",
            name="chess_com_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gamedataset",
            name="lichess_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
