# Generated by Django 4.2.26 on 2026-01-02 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0003_gamedataset_chess_com_username_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fen", models.CharField(db_index=True, max_length=200, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "evaluations_position",
                "ordering": ["fen"],
                "indexes": [
                    models.Index(fields=["fen"], name="evaluations_fen_159bc1_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="EvaluationData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("knodes", models.BigIntegerField()),
                ("depth", models.IntegerField()),
                ("pv_count", models.IntegerField()),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evals",
                        to="analysis.positionevaluation",
                    ),
                ),
            ],
            options={
                "db_table": "evaluations_data",
                "ordering": ["-pv_count", "-knodes"],
            },
        ),
        migrations.CreateModel(
            name="PrincipalVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pv_index", models.IntegerField()),
                ("cp", models.IntegerField(blank=True, null=True)),
                ("mate", models.IntegerField(blank=True, null=True)),
                ("line", models.TextField()),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pvs",
                        to="analysis.evaluationdata",
                    ),
                ),
            ],
            options={
                "db_table": "evaluations_pv",
                "ordering": ["pv_index"],
                "indexes": [
                    models.Index(
                        fields=["evaluation", "pv_index"],
                        name="evaluations_evaluat_a8d0f3_idx",
                    ),
                    models.Index(fields=["cp"], name="evaluations_cp_cb3a7c_idx"),
                    models.Index(fields=["mate"], name="evaluations_mate_e4d6d3_idx"),
                ],
                "unique_together": {("evaluation", "pv_index")},
            },
        ),
        migrations.AddIndex(
            model_name="evaluationdata",
            index=models.Index(
                fields=["position", "-pv_count"], name="evaluations_positio_f4c67a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evaluationdata",
            index=models.Index(fields=["knodes"], name="evaluations_knodes_bbfdf7_idx"),
        ),
        migrations.AddIndex(
            model_name="evaluationdata",
            index=models.Index(fields=["depth"], name="evaluations_depth_1aa6eb_idx"),
        ),
    ]
