# Generated by Django 4.2.26 on 2026-01-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analysis",
            "0004_positionevaluation_evaluationdata_principalvariation_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="gamedataset",
            name="newest_game_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gamedataset",
            name="oldest_game_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
