# Generated by Django 4.2.26 on 2026-01-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0005_gamedataset_newest_game_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="board_theme",
            field=models.CharField(
                choices=[
                    ("blue", "Blue Theme"),
                    ("green", "Green Theme"),
                    ("brown", "Brown Theme"),
                ],
                default="blue",
                help_text="Choose your preferred chessboard theme",
                max_length=20,
            ),
        ),
    ]
