# Generated by Django 4.2.26 on 2026-01-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0006_userprofile_board_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisreport",
            name="enriched_games",
            field=models.JSONField(default=list),
        ),
    ]
