# Generated by Django 4.2.26 on 2026-01-10 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0008_reportgenerationtask"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChessGame",
        ),
    ]
