# Generated by Django 4.2.26 on 2026-01-12 19:44

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


def create_gin_indexes(apps, schema_editor):
    """Create GIN indexes only on PostgreSQL"""
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(
            "CREATE INDEX puzzles_themes_gin_idx ON puzzles USING gin (themes gin_trgm_ops);"
        )
        schema_editor.execute(
            "CREATE INDEX puzzles_opening_tags_gin_idx ON puzzles USING gin (opening_tags gin_trgm_ops);"
        )


def drop_gin_indexes(apps, schema_editor):
    """Drop GIN indexes only on PostgreSQL"""
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("DROP INDEX IF EXISTS puzzles_themes_gin_idx;")
        schema_editor.execute("DROP INDEX IF EXISTS puzzles_opening_tags_gin_idx;")


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0009_remove_chessgame"),
    ]

    operations = [
        migrations.CreateModel(
            name="Puzzle",
            fields=[
                (
                    "puzzle_id",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("fen", models.CharField(db_index=True, max_length=200)),
                ("moves", models.CharField(max_length=500)),
                ("rating", models.IntegerField(db_index=True)),
                ("rating_deviation", models.IntegerField()),
                ("popularity", models.IntegerField()),
                ("nb_plays", models.IntegerField()),
                ("themes", models.TextField()),
                ("game_url", models.CharField(blank=True, max_length=500)),
                ("opening_tags", models.TextField(blank=True, db_index=True)),
            ],
            options={
                "db_table": "puzzles",
                "ordering": ["rating"],
                "indexes": [
                    models.Index(fields=["rating"], name="puzzles_rating_8bb9ad_idx"),
                    models.Index(fields=["fen"], name="puzzles_fen_52f5a3_idx"),
                    models.Index(
                        fields=["opening_tags"], name="puzzles_opening_4b4ad0_idx"
                    ),
                    models.Index(
                        fields=["rating", "popularity"],
                        name="puzzles_rating_34c86e_idx",
                    ),
                    models.Index(
                        fields=["rating", "nb_plays"], name="puzzles_rating_1ab79c_idx"
                    ),
                ],
            },
        ),

        # Enable PostgreSQL trigram extension for better text search (PostgreSQL only)
        migrations.RunPython(
            code=lambda apps, schema_editor: (
                schema_editor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
                if schema_editor.connection.vendor == 'postgresql'
                else None
            ),
            reverse_code=lambda apps, schema_editor: None,
        ),

        # Add GIN indexes for fast text search on themes and opening_tags (PostgreSQL only)
        migrations.RunPython(
            code=create_gin_indexes,
            reverse_code=drop_gin_indexes,
        ),
    ]
