# Generated by Django 4.2.26 on 2026-01-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0010_puzzle"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisreport",
            name="custom_puzzles",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
