# Generated by Django 4.2.26 on 2026-01-14 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analysis", "0011_add_custom_puzzles_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolvedBlunder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blunder_key", models.CharField(db_index=True, max_length=500)),
                ("solved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis.analysisreport",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "solved_blunders",
                "indexes": [
                    models.Index(
                        fields=["user", "report"], name="solved_blun_user_id_fe5de4_idx"
                    ),
                    models.Index(
                        fields=["blunder_key"], name="solved_blun_blunder_614dfa_idx"
                    ),
                ],
                "unique_together": {("user", "report", "blunder_key")},
            },
        ),
    ]
