# Generated by Django 4.2.26 on 2026-01-23 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analysis", "0012_solvedblunder"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolvedPuzzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puzzle_id", models.CharField(db_index=True, max_length=20)),
                ("solved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis.analysisreport",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "solved_puzzles",
                "indexes": [
                    models.Index(
                        fields=["user", "report"], name="solved_puzz_user_id_414a4b_idx"
                    ),
                    models.Index(
                        fields=["puzzle_id"], name="solved_puzz_puzzle__d9e036_idx"
                    ),
                ],
                "unique_together": {("user", "report", "puzzle_id")},
            },
        ),
    ]
