# Generated by Django 4.2.26 on 2026-01-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0013_solvedpuzzle"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisreport",
            name="elo_chart_data",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
