# Generated by Django 4.2.26 on 2026-01-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0014_analysisreport_elo_chart_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamedataset",
            name="elo_chart_data",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
