# Generated by Django 4.2.26 on 2026-01-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0015_gamedataset_elo_chart_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisreport",
            name="llm_insights",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
