# Generated by Django 4.2.26 on 2026-01-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0017_allow_null_depth_in_evaluation_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamedataset",
            name="analysis_generated",
            field=models.BooleanField(default=False),
        ),
    ]
