# Generated by Django 4.2.26 on 2026-01-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0018_add_analysis_generated_to_gamedataset"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamedataset",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
