# Generated by Django 4.2.26 on 2026-02-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0019_add_last_updated_to_gamedataset"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="games_analyzed_this_month",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="subscription_current_period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="subscription_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="subscription_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("standard", "Standard - $3/month"),
                    ("max", "Max - $9/month"),
                ],
                help_text="Current subscription tier",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="usage_reset_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
