#!/usr/bin/env python3
"""
Enrich opening statistics files with Stockfish analysis.

This script takes an opening stats file generated by generate_top_100_opening_stats.py
and enriches it by analyzing each FEN position from the top 3 blunders, mistakes, and
inaccuracies. For each position, it finds:
- The best move according to Stockfish
- The principal variation (sequence of best moves)
- Evaluation score

The enriched data is injected back into the JSON file.

Usage:
    python enrich_opening_stats.py <stats_file> [options]

Examples:
    # Enrich a stats file using local Stockfish
    python enrich_opening_stats.py static/data/top_100_opening_stats/700-800.json

    # Use remote Stockfish API
    python enrich_opening_stats.py static/data/top_100_opening_stats/700-800.json --api-url https://stockfish.example.com

    # Custom depth
    python enrich_opening_stats.py static/data/top_100_opening_stats/700-800.json --depth 15
"""

import json
import argparse
import sys
import time
import requests
from pathlib import Path
from typing import Dict, List, Optional, Set
import chess
import chess.engine

# Default Stockfish settings matching gcp-stockfish-api/stockfish_api.py
DEFAULT_DEPTH = 12
DEFAULT_TIME_LIMIT = 0.2  # 200ms per position


def find_stockfish() -> Optional[str]:
    """
    Auto-detect Stockfish installation.

    Returns:
        Path to Stockfish binary or None if not found
    """
    possible_paths = [
        "/usr/local/bin/stockfish",
        "/usr/bin/stockfish",
        "stockfish",
        "/opt/stockfish/stockfish"
    ]

    for path in possible_paths:
        try:
            with chess.engine.SimpleEngine.popen_uci(path) as engine:
                return path
        except:
            continue
    return None


def evaluate_position_local(fen: str, stockfish_path: str, depth: int = DEFAULT_DEPTH) -> Dict:
    """
    Evaluate a position using local Stockfish.

    Args:
        fen: FEN notation of the position
        stockfish_path: Path to Stockfish binary
        depth: Search depth

    Returns:
        Dict with evaluation, best move, and variation
    """
    try:
        with chess.engine.SimpleEngine.popen_uci(stockfish_path) as engine:
            # Configure engine to match API settings
            engine.configure({"Threads": 1, "Hash": 128})

            board = chess.Board(fen)

            # Analyze with same settings as API
            analysis = engine.analyse(
                board,
                chess.engine.Limit(depth=depth, time=DEFAULT_TIME_LIMIT)
            )

            # Extract score
            score = analysis['score'].white()
            if score.is_mate():
                mate_moves = score.mate()
                evaluation = 9999 if mate_moves > 0 else -9999
                mate_in = mate_moves
            else:
                evaluation = score.score() if score.score() is not None else 0
                mate_in = None

            result = {
                "evaluation": evaluation,
                "depth": depth
            }

            if mate_in is not None:
                result["mate"] = mate_in

            # Extract best move and variation
            if 'pv' in analysis and analysis['pv']:
                pv_moves = analysis['pv']

                if pv_moves:
                    result["best_move"] = pv_moves[0].uci()

                    # Create variation string (algebraic notation)
                    variation_moves = []
                    temp_board = board.copy()

                    for move in pv_moves[:10]:  # First 10 moves
                        if move in temp_board.legal_moves:
                            algebraic_move = temp_board.san(move)
                            variation_moves.append(algebraic_move)
                            temp_board.push(move)
                        else:
                            break

                    if variation_moves:
                        result["variation"] = " ".join(variation_moves)

            return result

    except Exception as e:
        return {"error": str(e)}


def evaluate_positions_api(fens: List[str], api_url: str, depth: int = DEFAULT_DEPTH) -> Dict[str, Dict]:
    """
    Evaluate multiple positions using remote Stockfish API.

    Args:
        fens: List of FEN strings
        api_url: URL of Stockfish API
        depth: Search depth

    Returns:
        Dict mapping FEN to evaluation result
    """
    try:
        response = requests.post(
            f"{api_url}/evaluate",
            json={
                "positions": fens,
                "depth": depth
            },
            timeout=300  # 5 minute timeout for large batches
        )
        response.raise_for_status()

        data = response.json()
        results = data.get("results", {})

        # Rename "best" to "best_move" for consistency
        for fen, result in results.items():
            if "best" in result:
                result["best_move"] = result.pop("best")

        return results

    except Exception as e:
        print(f"Error calling API: {e}")
        return {}


def load_eco_database(eco_file: Path) -> Dict[str, Dict[str, str]]:
    """
    Load the Lichess ECO database TSV file.

    Args:
        eco_file: Path to lichess_eco_database.tsv

    Returns:
        Dict mapping opening name to {pgn, fen, eco}
    """
    openings = {}

    with open(eco_file, 'r', encoding='utf-8') as f:
        # Skip header line
        next(f)

        for line in f:
            line = line.strip()
            if not line:
                continue

            parts = line.split('\t')
            if len(parts) >= 5:
                eco, name, pgn, uci, epd = parts[:5]
                openings[name] = {
                    'eco': eco,
                    'pgn': pgn,
                    'fen': epd
                }

    return openings


def collect_fens_from_stats(stats: Dict) -> Set[str]:
    """
    Collect all unique FEN positions from the stats file.

    Args:
        stats: Opening stats dictionary

    Returns:
        Set of unique FEN strings
    """
    fens = set()

    for speed_data in stats.values():
        if not isinstance(speed_data, dict):
            continue

        for opening_data in speed_data.values():
            if not isinstance(opening_data, dict):
                continue

            # Collect FENs from top 3 blunders, mistakes, and inaccuracies
            for error_type in ['top_3_blunders', 'top_3_mistakes', 'top_3_inaccuracies']:
                errors = opening_data.get(error_type, [])
                for error in errors:
                    if isinstance(error, dict) and 'fen' in error:
                        fens.add(error['fen'])

    return fens


def enrich_stats_with_opening_fens(stats: Dict, eco_database: Dict[str, Dict[str, str]]) -> int:
    """
    Enrich the stats dictionary with opening FEN positions from ECO database.

    Args:
        stats: Opening stats dictionary
        eco_database: Dict mapping opening name to {pgn, fen, eco}

    Returns:
        Number of openings enriched with FEN
    """
    enriched_count = 0

    for speed_data in stats.values():
        if not isinstance(speed_data, dict):
            continue

        for opening_name, opening_data in speed_data.items():
            if not isinstance(opening_data, dict):
                continue

            # Try to find the opening in the ECO database
            if opening_name in eco_database:
                eco_entry = eco_database[opening_name]
                opening_data['opening_fen'] = eco_entry['fen']
                opening_data['opening_pgn'] = eco_entry['pgn']
                enriched_count += 1
            else:
                # If exact match not found, log it for debugging
                print(f"    Warning: Opening '{opening_name}' not found in ECO database")

    return enriched_count


def enrich_stats_with_evaluations(stats: Dict, evaluations: Dict[str, Dict]) -> Dict:
    """
    Enrich the stats dictionary with Stockfish evaluations.

    Args:
        stats: Opening stats dictionary
        evaluations: Dict mapping FEN to evaluation result

    Returns:
        Enriched stats dictionary
    """
    enriched_count = 0

    for speed_data in stats.values():
        if not isinstance(speed_data, dict):
            continue

        for opening_data in speed_data.values():
            if not isinstance(opening_data, dict):
                continue

            # Enrich top 3 blunders, mistakes, and inaccuracies
            for error_type in ['top_3_blunders', 'top_3_mistakes', 'top_3_inaccuracies']:
                errors = opening_data.get(error_type, [])
                for error in errors:
                    if isinstance(error, dict) and 'fen' in error:
                        fen = error['fen']
                        if fen in evaluations:
                            eval_data = evaluations[fen]

                            # Add evaluation data to the error entry
                            if 'error' not in eval_data:
                                error['best_move'] = eval_data.get('best_move')
                                error['variation'] = eval_data.get('variation')
                                error['evaluation'] = eval_data.get('evaluation')
                                if 'mate' in eval_data:
                                    error['mate'] = eval_data['mate']
                                enriched_count += 1

    # Mark file as enriched
    stats['_enriched'] = True
    stats['_enrichment_timestamp'] = time.strftime('%Y-%m-%d %H:%M:%S')

    return stats, enriched_count


def enrich_opening_stats(
    stats_file: Path,
    api_url: Optional[str] = None,
    stockfish_path: Optional[str] = None,
    depth: int = DEFAULT_DEPTH,
    batch_size: int = 80,
    eco_database_path: Optional[Path] = None
) -> None:
    """
    Enrich an opening stats file with Stockfish analysis and opening FENs.

    Args:
        stats_file: Path to the stats JSON file
        api_url: Optional URL for remote Stockfish API
        stockfish_path: Optional path to local Stockfish binary
        depth: Search depth for analysis
        batch_size: Number of positions per API batch (for API mode)
        eco_database_path: Optional path to lichess_eco_database.tsv
    """
    print(f"Loading stats from {stats_file}...")

    # Load stats file
    with open(stats_file, 'r') as f:
        stats = json.load(f)

    # Load ECO database
    if eco_database_path is None:
        # Default path relative to script location
        script_dir = Path(__file__).parent
        eco_database_path = script_dir.parent / 'static' / 'data' / 'openings' / 'lichess_eco_database.tsv'

    if eco_database_path.exists():
        print(f"Loading ECO database from {eco_database_path}...")
        eco_database = load_eco_database(eco_database_path)
        print(f"Loaded {len(eco_database)} openings from ECO database")

        # Enrich with opening FENs
        print("Adding opening FEN positions...")
        fen_count = enrich_stats_with_opening_fens(stats, eco_database)
        print(f"Added opening FENs to {fen_count} openings")
    else:
        print(f"Warning: ECO database not found at {eco_database_path}")
        print("Skipping opening FEN enrichment")

    # Check if already enriched
    if stats.get('_enriched'):
        print(f"File already enriched at {stats.get('_enrichment_timestamp')}")
        response = input("Re-enrich anyway? (y/n): ")
        if response.lower() != 'y':
            print("Skipping enrichment")
            return
        # Remove enrichment markers to re-enrich
        stats.pop('_enriched', None)
        stats.pop('_enrichment_timestamp', None)

    # Collect all unique FENs
    print("Collecting FEN positions...")
    fens = collect_fens_from_stats(stats)
    print(f"Found {len(fens)} unique positions to analyze")

    if not fens:
        print("No positions to analyze")
        return

    # Evaluate positions
    evaluations = {}

    if api_url:
        # Use remote API in batches
        print(f"Using remote Stockfish API at {api_url}")
        fens_list = list(fens)

        for i in range(0, len(fens_list), batch_size):
            batch = fens_list[i:i + batch_size]
            batch_num = (i // batch_size) + 1
            total_batches = (len(fens_list) + batch_size - 1) // batch_size

            print(f"Processing batch {batch_num}/{total_batches} ({len(batch)} positions)...")

            batch_results = evaluate_positions_api(batch, api_url, depth)
            evaluations.update(batch_results)

            print(f"  Completed {len(batch_results)} evaluations")

            # Brief pause between batches to avoid overwhelming API
            if i + batch_size < len(fens_list):
                time.sleep(0.5)

    else:
        # Use local Stockfish
        if stockfish_path is None:
            stockfish_path = find_stockfish()
            if not stockfish_path:
                print("ERROR: Stockfish not found. Please install Stockfish or provide API URL.")
                sys.exit(1)

        print(f"Using local Stockfish at {stockfish_path}")
        print(f"Analyzing {len(fens)} positions at depth {depth}...")

        fens_list = list(fens)
        for i, fen in enumerate(fens_list, 1):
            if i % 10 == 0 or i == len(fens_list):
                print(f"  Progress: {i}/{len(fens_list)} positions analyzed")

            result = evaluate_position_local(fen, stockfish_path, depth)
            evaluations[fen] = result

    # Enrich stats with evaluations
    print("Enriching stats file...")
    stats, enriched_count = enrich_stats_with_evaluations(stats, evaluations)

    # Write back to file
    with open(stats_file, 'w') as f:
        json.dump(stats, f, indent=2)

    print(f"\n✓ Successfully enriched {enriched_count} positions")
    print(f"✓ Written to {stats_file}")
    print(f"✓ File marked as enriched")


def main():
    parser = argparse.ArgumentParser(
        description='Enrich opening statistics with Stockfish analysis.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Enrich using local Stockfish
  python enrich_opening_stats.py static/data/top_100_opening_stats/700-800.json

  # Use remote Stockfish API
  python enrich_opening_stats.py static/data/top_100_opening_stats/700-800.json --api-url https://stockfish-api.example.com

  # Custom depth and Stockfish path
  python enrich_opening_stats.py static/data/top_100_opening_stats/700-800.json --depth 15 --stockfish /usr/local/bin/stockfish

  # Batch size for API mode
  python enrich_opening_stats.py static/data/top_100_opening_stats/700-800.json --api-url https://stockfish-api.example.com --batch-size 50
        """
    )

    parser.add_argument('stats_file', help='Path to the opening stats JSON file')
    parser.add_argument('--api-url', type=str, default=None,
                        help='URL of remote Stockfish API (e.g., https://stockfish-api.example.com)')
    parser.add_argument('--stockfish', type=str, default=None,
                        help='Path to local Stockfish binary (auto-detected if not provided)')
    parser.add_argument('--depth', '-d', type=int, default=DEFAULT_DEPTH,
                        help=f'Analysis depth (default: {DEFAULT_DEPTH})')
    parser.add_argument('--batch-size', '-b', type=int, default=80,
                        help='Batch size for API requests (default: 80)')
    parser.add_argument('--eco-database', type=str, default=None,
                        help='Path to lichess_eco_database.tsv (default: static/data/openings/lichess_eco_database.tsv)')

    args = parser.parse_args()

    # Validate stats file
    stats_file = Path(args.stats_file)
    if not stats_file.exists():
        print(f"ERROR: Stats file not found: {stats_file}")
        sys.exit(1)

    # Validate depth
    if args.depth < 1 or args.depth > 50:
        print(f"ERROR: Depth must be between 1 and 50")
        sys.exit(1)

    # Prepare eco_database_path
    eco_db_path = Path(args.eco_database) if args.eco_database else None

    # Enrich the file
    try:
        enrich_opening_stats(
            stats_file,
            api_url=args.api_url,
            stockfish_path=args.stockfish,
            depth=args.depth,
            batch_size=args.batch_size,
            eco_database_path=eco_db_path
        )
    except KeyboardInterrupt:
        print("\n\nInterrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"\nERROR: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
